variables:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CI_BUILD_NUMBER: $(Build.BuildId)
  BRANCH_NAME: $(Build.SourceBranchName)
  TAG_NAME: $(Build.SourceBranchName)

# We don't need a CI trigger here, as the pipeline trigger starts this pipeline for master anyway.
trigger: none

resources:
  pipelines:
    - pipeline: ci-build
      source: Continuous-Integration-Test
      trigger:
        branches:
          include:
            - master

stages:
  - stage: Demo_for_Approval
    jobs:
      - deployment: Demo_Deploy
        displayName: Demo for Deployment with Approval
        pool:
          vmImage: 'ubuntu-20.04'
        # environment is created if it doesn't exist
        environment: ci-test-env
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none    # prevent automatic downloading of artifacts in deployment job
                - bash: echo "Hello from approved deployment"
