variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CI_BUILD_NUMBER: $(Build.BuildId)
  BRANCH_NAME: $(Build.SourceBranchName)
  TAG_NAME: $(Build.SourceBranchName)
  SDK_VERSION: 3.x

trigger:
  - master
  - ci-*
  - refs/tags/v*

pr:
  branches:
    include:
      - master

#schedules:
#  - cron: "0 0 * * *"
#    displayName: "Daily midnight build"
#    branches:
#      include:
#        - master

stages:
  - stage: Build_Test_Windows
    jobs:
      - template: jobs/build_and_test.yml
        parameters:
          name: windows
          vmImage: 'windows-2019'

  - stage: Build_Test_Linux
    dependsOn: [] # break sequential dependency
    jobs:
      - template: jobs/build_and_test.yml
        parameters:
          name: linux
          vmImage: 'ubuntu-18.04'

  - stage: Build_Test_MacOS
    dependsOn: [] # break sequential dependency
    jobs:
      - template: jobs/build_and_test.yml
        parameters:
          name: mac
          vmImage: 'macOS-10.15'

  - stage: Build_Docs
    dependsOn:
      - Build_Test_Windows
      - Build_Test_Linux
      - Build_Test_MacOS
    jobs:
      - template: jobs/build_docs.yml

  - stage: Deploy
    dependsOn:
      - Build_Test_Windows
      - Build_Test_Linux
      - Build_Test_MacOS
      - Build_Docs
    condition: and( succeeded(), startsWith( variables['Build.SourceBranch'], 'refs/tags' ) )
    jobs:
      - template: jobs/deploy_nuget.yml
      - template: jobs/deploy_docs.yml
