variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CI_BUILD_NUMBER: $(Build.BuildId)
  BRANCH_NAME: $(Build.SourceBranchName)
  TAG_NAME: $(Build.SourceBranchName)

jobs:
  - template: jobs/build_and_test.yml
    parameters:
      name: linux
      vmImage: 'ubuntu-16.04'
  
  - template: jobs/build_and_test.yml
    parameters:
      name: windows
      vmImage: 'vs2017-win2016'
  
  - template: jobs/build_and_test.yml
    parameters:
      name: mac
      vmImage: 'macOS-10.13'
