variables:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CI_BUILD_NUMBER: $(Build.BuildId)
  BRANCH_NAME: $(Build.SourceBranchName)
  TAG_NAME: $(Build.SourceBranchName)

trigger:
  - master
  - refs/tags/v*

pr:
  branches:
    include:
      - master

stages:
  - stage: Build_Test_Windows
    jobs:
      - template: jobs/build_and_test.yml
        parameters:
          name: windows
          vmImage: 'windows-2022'

  - stage: Build_Test_Linux
    dependsOn: [] # break sequential dependency
    jobs:
      - template: jobs/build_and_test.yml
        parameters:
          name: linux
          vmImage: 'ubuntu-20.04'

  - stage: Build_Test_MacOS
    dependsOn: [] # break sequential dependency
    jobs:
      - template: jobs/build_and_test.yml
        parameters:
          name: mac
          vmImage: 'macOS-11'

  - stage: Code_Coverage
    dependsOn:
      - Build_Test_Windows
      - Build_Test_Linux
      - Build_Test_MacOS
    jobs:
      - template: jobs/coverage.yml

  - stage: Deploy
    dependsOn:
      - Build_Test_Windows
      - Build_Test_Linux
      - Build_Test_MacOS
    condition: and( succeeded(), startsWith( variables['Build.SourceBranch'], 'refs/tags' ) )
    jobs:
      - template: jobs/deploy_nuget.yml
