variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CI_BUILD_NUMBER: $(Build.BuildId)
  BRANCH_NAME: $(Build.SourceBranchName)
  TAG_NAME: $(Build.SourceBranchName)

jobs:
  - template: jobs/build_and_test.yml
    parameters:
      name: linux
      vmImage: 'ubuntu-16.04'
  
  - template: jobs/build_and_test.yml
    parameters:
      name: windows
      vmImage: 'vs2017-win2016'
  
  - template: jobs/build_and_test.yml
    parameters:
      name: mac
      vmImage: 'macOS-10.13'

  - job: 'deploy'
    dependsOn:
      - linux
      - windows
      - mac
    pool:
      vmImage: 'ubuntu-16.04'
    condition: startsWith( variables['Build.SourceBranch'], 'refs/tags' )
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: current
          artifactName: NuGet-Packed
          downloadPath: .
      - bash: |
          chmod u+x ./build.sh

          if [[ "$TAG_NAME" =~ ^v([0-9])\.([0-9])\.([0-9])(-(preview-[0-9]+))$ ]]; then
            ./build.sh deploy myget
          elif [[ "$TAG_NAME" =~ ^v([0-9])\.([0-9])\.([0-9])$ ]]; then
            ./build.sh deploy nuget
          else
            echo "no deploy, as $TAG_NAME does not match"
            echo ##vso[task.complete result=Skipped;]tag does not match for deploy
          fi
        displayName: 'deploy to myget / nuget'
