language: csharp
dist: trusty
mono: none
dotnet: 2.0.0
env:
    global:
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1
os:
    - linux
git:
    depth: 1
before_script:
    - dotnet restore
script:
    - dotnet build -c Release --no-restore
after_success:
    - find tests -name *.csproj | xargs -n1 dotnet test --no-build -c Release
