language: csharp
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono: none
os:
  - linux
git:
  depth: 1
dotnet: 1.0.3
before_script:
  - dotnet restore
script:
  - dotnet build -c Release
after_success:
  - find tests -name *.csproj -exec dotnet test --no-build -c Release {} \;
