language: csharp
dist: trusty
mono: none
dotnet: 2.1.4
env:
    global:
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1
os:
    - linux
git:
    depth: 3
branches:
    only:
        - master
before_script:
    - export CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    - export BRANCH_NAME=$(if [[ -n "$TRAVIS_PULL_REQUEST_BRANCH" ]]; then echo "$TRAVIS_PULL_REQUEST_BRANCH"; else echo "$TRAVIS_BRANCH"; fi)
    - export TAG_NAME=$TRAVIS_TAG
    - chmod ugo+x ./build.sh
script:
    - ./build.sh build
    - ./build.sh test
    - ./build.sh pack
#after_success:
#    - ./build.sh deploy myget
