language: csharp
dist: trusty
mono: none
os:
  - linux
  - osx
osx_images: xcode7.1
git:
  depth: 1
dotnet: 1.0.3
before_script:
  - dotnet restore
script:
  - dotnet build -c Release
after_success:
  - find tests -name *.csproj -exec dotnet test --no-build -c Release {} \;
