language: csharp
dist: trusty
mono: none
dotnet: 2.0.0
env:
    global:
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1
os:
    - linux
    - osx
osx_image: xcode8.2
git:
    depth: 3
before_script:
    - chmod ugo+x ./build.sh
script:
    - ./build.sh build
    - ./build.sh test
after_success:
    - ./build.sh deploy myget