version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
clone_depth: 1
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_build:
- cmd: dotnet restore
build:
  parallel: true
  verbosity: minimal
test_script:
- cmd: dotnet test --no-build -c Release tests\Calculator.Core.Tests\Calculator.Core.Tests.csproj