jobs:
  - job: linux
    displayName: 'linux build and test'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - bash: |
          chmod u+x ./build.sh
          ./build.sh build
          ./build.sh test
          ./build.sh pack
      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: '**/*.trx'
  
  - job: windows
    displayName: 'windows build and test'
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - bash: |
          chmod u+x ./build.sh
          ./build.sh build
          ./build.sh test
          ./build.sh pack
      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: '**/*.trx'
  
  - job: mac
    displayName: 'mac build and test'
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - bash: |
          chmod u+x ./build.sh
          ./build.sh build
          ./build.sh test
          ./build.sh pack
      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: '**/*.trx'
