jobs:
  - template: .azure-jobs/build_and_test.yml
    parameters:
      name: linux
      vmImage: 'ubuntu-16.04'
  
  - template: .azure-jobs/build_and_test.yml
    parameters:
      name: windows
      vmImage: 'vs2017-win2016'
  
  - template: .azure-jobs/build_and_test.yml
    parameters:
      name: mac
      vmImage: 'macOS-10.13'
