# Environment variables on project-level:
# https://bitbucket.org/gfoidltests/continuous-integration-test/admin/addon/admin/pipelines/repository-variables
# NAME   Calculator.Core

image:
    name: microsoft/dotnet:2.0.4-sdk-2.1.3

clone:
    depth: 1

pipelines:
    tags:
        v*:
            - step:
                script:
                    - chmod ugo+x ./build.sh
                    - ./build.sh build
                    - ./build.sh test
                    #- ./build.sh deploy nuget
    branches:
        master:
            - step:
                script:
                    - chmod ugo+x ./build.sh
                    - ./build.sh build
                    - ./build.sh test
                    #- ./build.sh deploy myget
    default:
        - step:
            script:
                - chmod ugo+x ./build.sh
                - ./build.sh build
                - ./build.sh test
