# Environment variables on project-level:
# https://bitbucket.org/gfoidltests/continuous-integration-test/admin/addon/admin/pipelines/repository-variables
# NAME   Calculator.Core

image:
    name: microsoft/dotnet:2.0.0-sdk

clone:
    depth: 1

pipelines:
    tags:
        v*:
            - step:
                script:
                    - chmod ugo+x ./build.sh
                    - export CI_BUILD_NUMBER=$BITBUCKET_BUILD_NUMBER
                    - export BRANCH_NAME=$BITBUCKET_BRANCH
                    - export TAG_NAME=$BITBUCKET_TAG
                    - ./build.sh build
                    - ./build.sh test
                    #- ./build.sh deploy nuget
    branches:
        master:
            - step:
                script:
                    - chmod ugo+x ./build.sh
                    - export CI_BUILD_NUMBER=$BITBUCKET_BUILD_NUMBER
                    - export BRANCH_NAME=$BITBUCKET_BRANCH
                    - export TAG_NAME=$BITBUCKET_TAG
                    - ./build.sh build
                    - ./build.sh test
                    #- ./build.sh deploy myget
    default:
        - step:
            script:
                - chmod ugo+x ./build.sh
                - export CI_BUILD_NUMBER=$BITBUCKET_BUILD_NUMBER
                - export BRANCH_NAME=$BITBUCKET_BRANCH
                - export TAG_NAME=$BITBUCKET_TAG
                - ./build.sh build
                - ./build.sh test
