# Environment variables on project-level:
# https://bitbucket.org/gfoidltests/continuous-integration-test/admin/addon/admin/pipelines/repository-variables
# NAME   Calculator.Core

image:
    name: mcr.microsoft.com/dotnet/core/sdk:3.0

clone:
    depth: 1

pipelines:
    default:
        - step:
            script:
                - export CI_BUILD_NUMBER=$BITBUCKET_BUILD_NUMBER
                - export BRANCH_NAME=$BITBUCKET_BRANCH
                - export TAG_NAME=$BITBUCKET_TAG
                - chmod ugo+x ./build.sh
                - ./build.sh build
                - ./build.sh test
                - ./build.sh pack
