# Environment variables on project-level:
# https://bitbucket.org/gfoidltests/continuous-integration-test/admin/addon/admin/pipelines/repository-variables
# NAME   Calculator.Core

image:
    name: microsoft/dotnet:2.1-sdk

clone:
    depth: 1

pipelines:
    default:
        - step:
            script:
                - chmod ugo+x ./build.sh
                - ./build.sh build
                - ./build.sh test
                - ./build.sh pack
