image:
    name: microsoft/dotnet

clone:
    depth: 1

pipelines:
    default:
        - step:
            script:
                - echo "Branch -> $BITBUCKET_BRANCH    Commit -> $BITBUCKET_COMMIT"
                - dotnet restore
                - dotnet build -c Release --no-restore
                - find tests -name *.csproj | xargs -n1 dotnet test --no-build -c Release
