jobs:
  - job: coverage_report_quality
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      # checkout is needed for file-references
      #- checkout: none

      - task: DownloadPipelineArtifact@2
        inputs:
          targetPath: './coverage'

      - bash: |
            cd coverage
            ls -la
            echo ""

            for artifact in ./Coverage-*; do
                echo "artifact: $artifact"

                for coverage in $artifact/*; do
                    echo "  coverage: $coverage"
                    mv $coverage $(dirname $coverage).xml
                done

                rm -rf $artifact
            done

            echo ""
            ls -la
        displayName: fix artifact locations

      - bash: |
            echo "check if dotnet-reportgenerator-globaltool is installed..."

            if [[ $(dotnet tool list -g | grep dotnet-reportgenerator-globaltool | wc -l) -eq 0 ]]; then
                echo "not installed -> will install it"
                export PATH="$PATH:$HOME/.dotnet/tools"
                dotnet tool install -g dotnet-reportgenerator-globaltool
            else
                echo "already installed"
            fi

            echo ""

            reportgenerator -reports:coverage/Coverage-*.xml -targetdir:coverage/Report -reporttypes:"Cobertura;HtmlInline_AzurePipelines"
        displayName: Report generation

      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: 'coverage/Report/Cobertura.xml'
          reportDirectory: 'coverage/Report'

      # extension from Marketplace https://marketplace.visualstudio.com/acquisition?itemName=mspremier.BuildQualityChecks
      - task: BuildQualityChecks@6
        displayName: 'Check build quality'
        inputs:
          checkCoverage: true
          coverageFailOption: 'build'
          coverageType: 'lines'
          allowCoverageVariance: true
          coverageVariance: '0.5'
          baseBranchRef: 'master'
