jobs:
  - job: coverage_report_quality
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      # checkout is needed for file-references
      #- checkout: none

      - task: DownloadPipelineArtifact@2
        inputs:
          targetPath: './coverage'

      - bash: |
            cd coverage
            ls -la
            echo ""

            for artifact in ./Coverage-*; do
                echo "artifact: $artifact"

                for coverage in $artifact/*; do
                    echo "  coverage: $coverage"
                    mv $coverage $(dirname $coverage).xml
                done

                rm -rf $artifact
            done

            echo ""
            ls -la
        displayName: fix artifact locations

      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: coverage/Coverage-*.xml  

      # extension from Marketplace https://marketplace.visualstudio.com/acquisition?itemName=mspremier.BuildQualityChecks
      - task: BuildQualityChecks@6
        displayName: 'Check build quality'
        inputs:
          checkCoverage: true
          coverageFailOption: 'build'
          coverageType: 'lines'
          allowCoverageVariance: true
          coverageVariance: '0.5'
          baseBranchRef: 'master'
