jobs:
  - job: coverage_report_quality
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      # checkout is needed for file-references
      #- checkout: none

      # Here we download all, as we have several Cobertura.xml files for each
      # build configuration.
      - task: DownloadPipelineArtifact@2
        inputs:
          targetPath: './coverage'

      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: 'coverage/**/Cobertura.xml'
          pathToSources: $(System.DefaultWorkingDirectory)

      # extension from Marketplace https://marketplace.visualstudio.com/items?itemName=mspremier.BuildQualityChecks
      - task: BuildQualityChecks@8
        displayName: 'check build quality'
        inputs:
          showStatistics: true
          checkCoverage: true
          coverageFailOption: 'build'
          coverageType: 'blocks'
          allowCoverageVariance: true
          coverageVariance: '0.5'
          fallbackOnPRTargetBranch: false
          baseBranchRef: 'master'
