jobs:
  - job: cygwin_test
    pool:
      vmImage: 'windows-2019'
    steps:
      - task: PowerShell@2
        displayName: install cygwin
        inputs:
          filePath: 'tests/cygwin_test/install_cygwin.ps1'

      - bash: echo "##vso[task.setvariable TEST_EXIT_CODE=0;]0"
        displayName: set TEST_EXIT_CODE 0

      - task: CmdLine@2
        displayName: exit code 0
        inputs:
          script: 'C:\cygwinx86_x64\bin\bash.exe --login $(System.DefaultWorkingDirectory)\tests\cygwin_test\my_script.sh'

      - bash: echo "##vso[task.setvariable TEST_EXIT_CODE=1;]1"
        displayName: set TEST_EXIT_CODE 1

      - task: CmdLine@2
        displayName: exit code 1
        inputs:
          script: |
              'C:\cygwinx86_x64\bin\bash.exe --login $(System.DefaultWorkingDirectory)\tests\cygwin_test\my_script.sh'

              if errorlevel 1 exit 0

              exit 1
