version: 2
defaults: &defaults
    working_directory: ~/repo
    docker:
        - image: microsoft/dotnet:2.0.0-sdk
          environment:
            DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
            DOTNET_CLI_TELEMETRY_OPTOUT: 1
jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - run: chmod ugo+x ./build.sh
            - run:
                name: build
                command: |
                    export CI_BUILD_NUMBER=$CIRCLE_BUILD_NUM
                    export BRANCH_NAME=$CIRCLE_BRANCH
                    export TAG_NAME=$CIRCLE_TAG
                    ./build.sh build
            - persist_to_workspace:
                root: .
                paths:
                    - source/**/bin
                    - tests/**/bin
    test:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                at: .
            - run: chmod ugo+x ./build.sh
            - run: ./build.sh test
    deploy_nuget:
        <<: *defaults
        steps:
            - attach_workspace:
                at: .
            - run: chmod ugo+x ./build.sh
            - run: ./build.sh deploy nuget
    deploy_myget:
        <<: *defaults
        steps:
            - attach_workspace:
                at: .
            - run: chmod ugo+x ./build.sh
            - run: ./build.sh deploy myget
        
workflows:
    version: 2
    build_and_test:
        jobs:
            - build:
                filters:
                    tags:
                        only: /^v[0-9]\.[0-9]\.[0-9]$/
            - test:
                requires:
                    - build
                filters:
                    tags:
                        only: /^v[0-9]\.[0-9]\.[0-9]$/
            - deploy_nuget:
                requires:
                    - test
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^v[0-9]\.[0-9]\.[0-9]$/
                context: org-global
            - deploy_myget:
                requires:
                    - test
                filters:
                    branches:
                        only: master
                context: org-global