version: 2
defaults: &defaults
    working_directory: ~/repo
    docker:
        - image: microsoft/dotnet:2.0.0-sdk
          environment:
            DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
            DOTNET_CLI_TELEMETRY_OPTOUT: 1
jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - run: dotnet restore
            - run: dotnet build -c Release --no-restore
            - run: find tests -name *.csproj | xargs -n1 dotnet test --no-build -c Release
