version: 2
defaults: &defaults
    working_directory: ~/repo
    docker:
        - image: microsoft/dotnet:2.1-sdk
          environment:
            DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
            DOTNET_CLI_TELEMETRY_OPTOUT: 1
jobs:
    build_test_pack:
        <<: *defaults
        steps:
            - checkout
            - run:
                name: init
                command: |
                    chmod ugo+x ./build.sh

                    # Exporting the path before installing the tool prevents the message about the PATH
                    export PATH="$PATH:/root/.dotnet/tools"
                    dotnet tool install -g trx2junit
            - run:
                name: build
                command: ./build.sh build
            - run:
                name: test
                command: ./build.sh test
            - run:
                name: test results
                command: |
                    if [[ -d "tests/TestResults" ]]; then
                        find tests/TestResults -name "*.trx" | xargs -n1 trx2junit
                        rm tests/TestResults/*.trx
                    fi
                when: always
            - run:
                name: pack
                command: ./build.sh pack
            - persist_to_workspace:
                root: .
                paths:
                    - build.sh
                    - NuGet-Packed
            - store_test_results:
                path: tests/TestResults
            - store_artifacts:
                path: tests/TestResults
                destination: TestResults
    deploy_nuget:
        <<: *defaults
        steps:
            - attach_workspace:
                at: .
            - run:
                name: deploy to NuGet
                command: |
                    chmod ugo+x ./build.sh
                    ./build.sh deploy nuget
    deploy_myget:
        <<: *defaults
        steps:
            - attach_workspace:
                at: .
            - run:
                name: deploy to MyGet
                command: |
                    chmod ugo+x ./build.sh
                    ./build.sh deploy myget

workflows:
    version: 2
    build_test_deploy:
        jobs:
            - build_test_pack:
                filters:
                    tags:
                        only: /^v[0-9]\.[0-9]\.[0-9](-preview-[0-9]+)?$/
            - deploy_nuget:
                requires:
                    - build_test_pack
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^v[0-9]\.[0-9]\.[0-9]$/
                context: org-global
            - deploy_myget:
                requires:
                    - build_test_pack
                filters:
                    branches:
                        #only: master
                        ignore: /.*/
                    tags:
                        only: /^v[0-9]\.[0-9]\.[0-9](-preview-[0-9]+)?$/
                context: org-global
